#pragma once

#define CAMERA_SHUTTER 0
#define CAMERA_GAIN 1
#define CAMERA_WHITE_BALANCE_U 2
#define CAMERA_WHITE_BALANCE_V 3
#define CAMERA_BRIGHTNESS 4
#define CAMERA_GAMMA 5
#define CAMERA_HUE 6
#define CAMERA_SATURATION 7
#define CAMERA_SHARPNESS 8
#define CAMERA_RED_GAIN 9
#define CAMERA_GREEN_GAIN 10
#define CAMERA_BLUE_GAIN 11
#define CAMERA_COLOR_GAIN 12

#define NUM_CAMERA_CONTROLS 13

#define CAMERA_AUTO_WHITE_BALANCE 13
#define CAMERA_AUTO_INTENSITY 14
#define CAMERA_TARGET_INTENSITY 15
#define CAMERA_MIN_SHUTTER_AUTO_INTENSITY 16
#define CAMERA_MAX_SHUTTER_AUTO_INTENSITY 17

#define CACHE_CAMERA_GAIN_MIN 18
#define CACHE_CAMERA_GAIN_MAX 19
#define CACHE_CAMERA_SHUTTER_MIN 20
#define CACHE_CAMERA_SHUTTER_MAX 21
#define CACHE_CAMERA_WHITE_BALANCE_U_MIN 22
#define CACHE_CAMERA_WHITE_BALANCE_U_MAX 23
#define CACHE_CAMERA_WHITE_BALANCE_V_MIN 24
#define CACHE_CAMERA_WHITE_BALANCE_V_MAX 25
#define CACHE_CAMERA_BRIGHTNESS_MIN 26
#define CACHE_CAMERA_BRIGHTNESS_MAX 27
#define CACHE_CAMERA_GAMMA_MIN 28
#define CACHE_CAMERA_GAMMA_MAX 29
#define CACHE_CAMERA_HUE_MIN 30
#define CACHE_CAMERA_HUE_MAX 31
#define CACHE_CAMERA_SATURATION_MIN 32
#define CACHE_CAMERA_SATURATION_MAX 33
#define CACHE_CAMERA_SHARPNESS_MIN 34
#define CACHE_CAMERA_SHARPNESS_MAX 35
#define CACHE_CAMERA_RED_GAIN_MIN 36
#define CACHE_CAMERA_RED_GAIN_MAX 37
#define CACHE_CAMERA_GREEN_GAIN_MIN 38
#define CACHE_CAMERA_GREEN_GAIN_MAX 39
#define CACHE_CAMERA_BLUE_GAIN_MIN 40
#define CACHE_CAMERA_BLUE_GAIN_MAX 41
#define CACHE_CAMERA_COLOR_GAIN_MIN 42
#define CACHE_CAMERA_COLOR_GAIN_MAX 43

#define NUM_CAMERA_PROPERTIES 44
